%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
# 182.04010767430282, 181.96058158656675, 161.9195512794151, 153.77295468660398
Camera1.fx: 182.04010767430282
Camera1.fy: 181.96058158656675
Camera1.cx: 161.9195512794151
Camera1.cy: 153.77295468660398
# -0.07299056810312483, -0.00542929749945422, -0.0008660339277163717, 0.0006391558355095592]
Camera1.k1: -0.07299056810312483
Camera1.k2: -0.00542929749945422
Camera1.p1: -0.0008660339277163717
Camera1.p2: 0.0006391558355095592

# Camera resolution
Camera.width: 324
Camera.height: 244

Camera.newWidth: 600
Camera.newHeight: 350

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.006577236683859483, -0.9999782380729134, -0.0005131648826354751, -0.02919941674295791,
          -0.22460039902171453, 0.0019773459941815064, -0.9744489472835949, 1.1811080822848563,
          0.9744287561011793, -0.0062939243252180255, -0.224608516756817, 0.6743382860157909,
          0.0, 0.0, 0.0, 1.0]

# IMU noise

# IMU.NoiseGyro: 1.7e-3 #1.6968e-04
# IMU.NoiseAcc: 2.0000e-2 #2.0e-3
# IMU.GyroWalk: 1.9393e-05 
# IMU.AccWalk: 3.0000e-03 # 3e-03

IMU.NoiseGyro: 0.0002602984004119891 
IMU.NoiseAcc: 0.00017630383367353976 
IMU.GyroWalk: 2.0043114067565446e-05 
IMU.AccWalk: 3.432843394384884e-05 

# IMU.NoiseGyro: 1e-3 # rad/s^0.5
# IMU.NoiseAcc: 1e-2   # m/s^1.5
# IMU.GyroWalk: 1e-7 # rad/s^1.5
# IMU.AccWalk: 1e-7 # m/s^2.5

IMU.Frequency: 100.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid  
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid 
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast   
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 5

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
